server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://locslhost:3306/citigenDBs
    username: root
    password: root
    
  jpa:
    hibernate:
       ddl-auto: update
    database-platform: org.hibernate.dialect.MYSQL5inoDialect
  application:
    name: CITIZEN-SERVICE